### ISSUE TITLE
Auto-refresh support

### ISSUE THREAD

**Issue by tillias** [MCMicS/jenkins-control-plugin#196]
Is it possible to integrate automatic refresh (e.g. every 30 seconds)?

**Comment by MCMicS** [comment]
You can configure refresh rate for Jobs. This will schedule the refresh.
This will currently collapse all builds but the jobs are reloaded.

![grafik](https://user-images.githubusercontent.com/4604206/79251599-a3f6de00-7e80-11ea-8228-546ea349768c.png)

Or do you mean to make configurable for seconds instead of minutes?

**Comment by tillias** [comment]
It is exactly what I need, thanks for the help. Missed this configuration completely

**Comment by MCMicS** [comment]
You're welcome.
