### ISSUE TITLE
API Token not working

### ISSUE THREAD

**Issue by tillias** [MCMicS/jenkins-control-plugin#199]
Hello,

I'm not sure if it is bug or feature, but it seems I can't authenticate using API-Token.

Is it possible to choose somehow if password or token should be used for Jenkins auth?

Thanks

**Comment by tillias** [comment]
If I try to pass token using following format:
http://user:apiToken@jenkins.yourcompany.com/job/your_job/build?token=TOKEN then there is validation message in plugin, so I need to put it into "above form instead"

**Comment by MCMicS** [comment]
why you have to use this format? This form is a security risk in my option because the API token is saved as plain text.

It is possible to use following credentials:

User: <YourName>
Password: <API-TOKEN>
![grafik](https://user-images.githubusercontent.com/4604206/79889904-f5621880-83fe-11ea-932a-3b2de07f6622.png)
The you also not need a crumb token.

The authentification with API Token works. We have currently a bug if redirect is used (see #193)

For more infos see issue: #151

If you need more help please ask again or join the gitter channel.

**Comment by MCMicS** [comment]
If it not work feel free to reopen it

**Comment by tillias** [comment]
Well, on my side there is simple error "Unauthorized
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required."

Not sure if this is the same as #193

**Comment by MCMicS** [comment]
Hi,
could you check following command to verfiy your credentials?
`curl -v -u user:API_TOKEN https://<jenkinsUrl>/user/user/api/json`

**Comment by tillias** [comment]
Thanks for the fast response. Here is output:
```
*   Trying xx.yy.zz...
* Connected to sbs.t-systems.com (xx.yy.zz) port 443 (#0)
* found n certificates in /etc/ssl/certs/ca-certificates.crt
* found m certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: sbs.t-systems.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        compression: NULL
* ALPN, server accepted to use http/1.1
* Server auth using Basic with user 'login'
> GET /jenkins/user/user/api/json HTTP/1.1
> Host: jenkins.host
> Authorization: Basic aWx0ZXJub3Y6MTE3NThhYmE3MDYzOTNkMTRmM2I5MzNhMTI5MDU5MTViMQ==
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Wed, 22 Apr 2020 09:20:14 GMT
< Server: Apache
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="SomeRealm"
< Content-Length: 381
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
* Connection #0 to host jenkins.host left intact
```

**Comment by MCMicS** [comment]
This seems that your credentials are wrong.
Could you try to create a new API Token: http://jenkins.host/user/<name>/configure
`curl -v -u login:API_TOKEN https://jenkins.host/user/login/api/json`

It is possible that a legacy API Token will be rejected.

Do you have an Apache in front of the Jenkins which need authentification? Because your server Unauthorized response is from: "Server: Apache"

If you use an Apache to authentificate we have currently a bug: #160

**Comment by tillias** [comment]
Yes, Jenkins it seems it is exactly what #160 is

**Comment by MCMicS** [comment]
ok thanks for feedback
