### ISSUE TITLE
Password Parameter default value ignored

### ISSUE THREAD

**Issue by danekja** [MCMicS/jenkins-control-plugin#204]
We have jobs which have password parameters configured with default values. Despite the defaults set, the plugin forces us to fill-in those parameters every time we trigger the job from IDEA (which is very annoying).

Is there a way to get around this? The #203 feature would be one option. Maybe there is a simpler one (not sure what Jenkins API allows regarding password parameters).

If you could point me in the right direction, I would be happy to help with this.

IDEA version: IU-201.6668.121, built on April 8, 2020
Plugin version: 0.13.0-2020.1
Jenkins version: 2.222.1

**Comment by MCMicS** [comment]
Hi
Currently I have not see the default value in api. Maybe a security from jenkins (and I agree).

If you trigger the Job from Jenkins you also not see the password.

I test later what happens if jenkins use the default if not send from our plugin.

The it would be possible to check if password was entered and send it.
Or an additional Checkbox with use default.
