### ISSUE TITLE
FileParameterDefinition is unsupported

### ISSUE THREAD

**Issue by Ed-XCF** [MCMicS/jenkins-control-plugin#223]
My build requires a file parameter, but it is not necessary. But I can not build at my idea now. How could I build without upload file or how could my idea support file parameter.
Thanks :)

**Comment by MCMicS** [comment]
File is currently not implemented.
If it is not needed you could remove it from job.

But it should possible to implement the parameter. An workaround ist to name the file parameter to 'patch.xml' because it would handle as patch parameter

But this is only a hack :smile:

I will add the file parameter as supported in next release.

**Comment by Ed-XCF** [comment]
Awsome! I am looking forward to the next release.

**Comment by MCMicS** [comment]
closed by #226

**Comment by MCMicS** [comment]
released with [0.13.5](../releases/tag/v0.13.5)
